# Generated by Django 3.1.1 on 2020-10-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('publish_time', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('source', models.TextField()),
                ('category', models.TextField()),
                ('top_img', models.TextField()),
            ],
        ),
    ]
